package config

type UIConfig struct {
	Theme                  string `json:"theme"`
	Version                string `json:"version"`
	LogoImage              bool   `json:"logo_image"`
	LogoHeight             string `json:"logo_height"`
	LogoWidth              string `json:"logo_width"`
	Favicon                string `json:"favicon"`
	LogoLinkName           string `json:"logo_link_name"`
	LoginImage             string `json:"login_image"`
	FixedHeader            bool   `json:"fixed_header"`
	HeaderPadding          string `json:"header_padding"`
	NavLink1               string `json:"nav_link_1"`
	NavLink3               string `json:"nav_link_3"`
	NavLink4               string `json:"nav_link_4"`
	FixedFooter            bool   `json:"fixed_footer"`
	HideFooter             bool   `json:"hide_footer"`
	HeaderStyleClass       string `json:"header_style_class"`
	FooterStyleClass       string `json:"footer_style_class"`
	CssATagColor           string `json:"css_a_tag_color"`
	CssPTagColor           string `json:"css_p_tag_color"`
	FolderTextColor        string `json:"folder_text_color"`
	LoadingSpinnerClass    string `json:"loading_spinner_class"`
	SearchButtonClass      string `json:"search_button_class"`
	PathNavAlertClass      string `json:"path_nav_alert_class"`
	FileViewAlertClass     string `json:"file_view_alert_class"`
	FileCountAlertClass    string `json:"file_count_alert_class"`
	ContactLink            string `json:"contact_link"`
	CopyrightYear          string `json:"copyright_year"`
	CompanyName            string `json:"company_name"`
	CompanyLink            string `json:"company_link"`
	Credit                 bool   `json:"credit"`
	DisplaySize            bool   `json:"display_size"`
	DisplayTime            bool   `json:"display_time"`
	DisplayDownload        bool   `json:"display_download"`
	DisablePlayer          bool   `json:"disable_player"`
	DisableVideoDownload   bool   `json:"disable_video_download"`
	AllowSelectingFiles    bool   `json:"allow_selecting_files"`
	SecondDomainForDL      bool   `json:"second_domain_for_dl"`
	Poster                 string `json:"poster"`
	AudioPoster            string `json:"audioposter"`
	JsdelivrCDNSrc         string `json:"jsdelivr_cdn_src"`
	RenderHeadMD           bool   `json:"render_head_md"`
	RenderReadmeMD         bool   `json:"render_readme_md"`
	UnauthorizedOwnerLink  string `json:"unauthorized_owner_link"`
	UnauthorizedOwnerEmail string `json:"unauthorized_owner_email"`
	DownloadDomain         string `json:"downloaddomain"`
	ShowLogoutButton       bool   `json:"show_logout_button"`
}
